### ISSUE TITLE
LORSAL Implementation

### ISSUE THREAD

**Issue by jerofad** [Vikki23/Demo_spectral_spatial_hyperspectral_classification#2]
Hi. I cant find the LORSAL algorithm implemented here. is it still available?

**Comment by huyina** [comment]
Hi.I can't find some unction that the demos need, would you please update the codes?

**Comment by Vikki23** [comment]
> Hi. I cant find the LORSAL algorithm implemented here. is it still available?

Yes. I've uploaded all the files. Please recheck it. Hope u enjoy it! :)

**Comment by Vikki23** [comment]
> Hi.I can't find some unction that the demos need, would you please update the codes?

Yes. I've uploaded them. Enjoy :)

**Comment by huyina** [comment]
Thank you so much.发自我的华为手机-------- 原始邮件 --------主题：Re: [Vikki23/Demo_spectral_spatial_hyperspectral_classification] LORSAL Implementation (#2)发件人：Vikki23 收件人：Vikki23/Demo_spectral_spatial_hyperspectral_classification 抄送：huyina ,Comment 
Hi.I can't find some unction that the demos need, would you please update the codes?

Yes. I've uploaded them. Enjoy :)
